const data = {
    responseCode: "100",
    data: [
      {
        security_code: "DSBS",
        board: "Spot",
        price: 406139.53,
        lowest_price: 363600.0,
        location_code: "201",
        highest_price: 444400.0,
        created: "2022-06-16T09:14:50.489139Z",
        transaction_fee_configurations: [
          {
            order_type: "Buy",
            fee_name: "Exchange Fee",
            fee_description: null,
            fee_value: 975.0,
            fee_type: "fixed",
            fee_structure_type: "unit",
          },
          {
            order_type: "Buy",
            fee_name: "Sec Fee",
            fee_description: null,
            fee_value: 25.0,
            fee_type: "fixed",
            fee_structure_type: "unit",
          },
          {
            order_type: "Sell",
            fee_name: "Sec Fee",
            fee_description: null,
            fee_value: 25.0,
            fee_type: "fixed",
            fee_structure_type: "unit",
          },
          {
            order_type: "Sell",
            fee_name: "Exchange Fee",
            fee_description: null,
            fee_value: 975.0,
            fee_type: "fixed",
            fee_structure_type: "unit",
          },
        ],
      },
      {
        security_code: "DMAZ",
        board: "Spot",
        price: 29139.53,
        lowest_price: 21600.0,
        location_code: "201",
        highest_price: 26400.0,
        created: "2022-06-16T09:13:07.357206Z",
        transaction_fee_configurations: [
          {
            order_type: "Buy",
            fee_name: "Exchange Fee",
            fee_description: null,
            fee_value: 975.0,
            fee_type: "fixed",
            fee_structure_type: "unit",
          },
          {
            order_type: "Sell",
            fee_name: "Exchange Fee",
            fee_description: null,
            fee_value: 975.0,
            fee_type: "fixed",
            fee_structure_type: "unit",
          },
          {
            order_type: "Buy",
            fee_name: "Sec Fee",
            fee_description: null,
            fee_value: 25.0,
            fee_type: "fixed",
            fee_structure_type: "unit",
          },
          {
            order_type: "Sell",
            fee_name: "Sec Fee",
            fee_description: null,
            fee_value: 25.0,
            fee_type: "fixed",
            fee_structure_type: "unit",
          },
        ],
      },
      {
        security_code: "OSSC",
        board: "OTC",
        price: 205000.0,
        lowest_price: 205000.0,
        location_code: "131",
        highest_price: 205000.0,
        created: "2022-06-15T15:34:16Z",
        transaction_fee_configurations: [
          {
            order_type: "Buy",
            fee_name: "Exchange Fee",
            fee_description: "Exchange Fee",
            fee_value: 975.0,
            fee_type: "fixed",
            fee_structure_type: "unit",
          },
          {
            order_type: "Sell",
            fee_name: "Exchange Fee",
            fee_description: null,
            fee_value: 975.0,
            fee_type: "fixed",
            fee_structure_type: "unit",
          },
          {
            order_type: "Buy",
            fee_name: "SEC Fee",
            fee_description: null,
            fee_value: 25.0,
            fee_type: "fixed",
            fee_structure_type: "unit",
          },
          {
            order_type: "Sell",
            fee_name: "SEC Fee",
            fee_description: null,
            fee_value: 25.0,
            fee_type: "fixed",
            fee_structure_type: "unit",
          },
        ],
      },
      {
        security_code: "OMAZ",
        board: "OTC",
        price: 207000.0,
        lowest_price: 207000.0,
        location_code: "021",
        highest_price: 207000.0,
        created: "2022-06-15T15:31:32Z",
        transaction_fee_configurations: [
          {
            order_type: "Sell",
            fee_name: "SEC Fee",
            fee_description: null,
            fee_value: 25.0,
            fee_type: "fixed",
            fee_structure_type: "unit",
          },
          {
            order_type: "Buy",
            fee_name: "SEC Fee",
            fee_description: null,
            fee_value: 25.0,
            fee_type: "fixed",
            fee_structure_type: "unit",
          },
          {
            order_type: "Sell",
            fee_name: "Exchange Fee",
            fee_description: null,
            fee_value: 2000.0,
            fee_type: "fixed",
            fee_structure_type: "unit",
          },
          {
            order_type: "Buy",
            fee_name: "Exchange Fee",
            fee_description: null,
            fee_value: 0.0,
            fee_type: "fixed",
            fee_structure_type: "unit",
          },
        ],
      },
      {
        security_code: "SSBS",
        board: "Spot",
        price: 450.0,
        lowest_price: 440.0,
        location_code: "",
        highest_price: 450.0,
        created: "2022-06-17T09:26:17Z",
        transaction_fee_configurations: [
          {
            order_type: "Buy",
            fee_name: "Exchange Fee",
            fee_description: null,
            fee_value: 0.5,
            fee_type: "percentage",
            fee_structure_type: "unit",
          },
          {
            order_type: "Buy",
            fee_name: "SEC Fee",
            fee_description: null,
            fee_value: 0.3,
            fee_type: "percentage",
            fee_structure_type: "unit",
          },
          {
            order_type: "Sell",
            fee_name: "Exchange Fee",
            fee_description: null,
            fee_value: 0.5,
            fee_type: "percentage",
            fee_structure_type: "unit",
          },
          {
            order_type: "Sell",
            fee_name: "Collateral Management",
            fee_description: null,
            fee_value: 0.7,
            fee_type: "percentage",
            fee_structure_type: "unit",
          },
          {
            order_type: "Buy",
            fee_name: "VAT",
            fee_description: null,
            fee_value: 7.5,
            fee_type: "vat",
            fee_structure_type: "unit",
          },
          {
            order_type: "Sell",
            fee_name: "VAT",
            fee_description: null,
            fee_value: 7.5,
            fee_type: "vat",
            fee_structure_type: "unit",
          },
        ],
      },
      {
        security_code: "SSGM",
        board: "Spot",
        price: 230.0,
        lowest_price: 210.0,
        location_code: "",
        highest_price: 230.0,
        created: "2022-06-16T09:27:51Z",
        transaction_fee_configurations: [
          {
            order_type: "Buy",
            fee_name: "Exchange Fee",
            fee_description: null,
            fee_value: 0.5,
            fee_type: "percentage",
            fee_structure_type: "unit",
          },
          {
            order_type: "Buy",
            fee_name: "SEC Fee",
            fee_description: null,
            fee_value: 0.3,
            fee_type: "percentage",
            fee_structure_type: "unit",
          },
          {
            order_type: "Sell",
            fee_name: "Exchange Fee",
            fee_description: null,
            fee_value: 0.5,
            fee_type: "percentage",
            fee_structure_type: "unit",
          },
          {
            order_type: "Sell",
            fee_name: "Collateral Management",
            fee_description: null,
            fee_value: 0.7,
            fee_type: "percentage",
            fee_structure_type: "unit",
          },
          {
            order_type: "Buy",
            fee_name: "VAT",
            fee_description: null,
            fee_value: 7.5,
            fee_type: "vat",
            fee_structure_type: "unit",
          },
          {
            order_type: "Sell",
            fee_name: "VAT",
            fee_description: null,
            fee_value: 7.5,
            fee_type: "vat",
            fee_structure_type: "unit",
          },
        ],
      },
      {
        security_code: "SMAZ",
        board: "Spot",
        price: 202.0,
        lowest_price: 181.8,
        location_code: "",
        highest_price: 222.2,
        created: "2022-06-16T09:17:07Z",
        transaction_fee_configurations: [
          {
            order_type: "Buy",
            fee_name: "VAT",
            fee_description: null,
            fee_value: 7.5,
            fee_type: "vat",
            fee_structure_type: "unit",
          },
          {
            order_type: "Sell",
            fee_name: "VAT",
            fee_description: null,
            fee_value: 7.5,
            fee_type: "vat",
            fee_structure_type: "unit",
          },
          {
            order_type: "Buy",
            fee_name: "Exchange Fee",
            fee_description: null,
            fee_value: 0.5,
            fee_type: "percentage",
            fee_structure_type: "unit",
          },
          {
            order_type: "Buy",
            fee_name: "SEC Fee",
            fee_description: null,
            fee_value: 0.3,
            fee_type: "percentage",
            fee_structure_type: "unit",
          },
          {
            order_type: "Sell",
            fee_name: "Exchange Fee",
            fee_description: null,
            fee_value: 0.5,
            fee_type: "percentage",
            fee_structure_type: "unit",
          },
          {
            order_type: "Sell",
            fee_name: "Collateral Management",
            fee_description: null,
            fee_value: 0.7,
            fee_type: "percentage",
            fee_structure_type: "unit",
          },
        ],
      },
      {
        security_code: "SCOC",
        board: "Spot",
        price: 1000.0,
        lowest_price: 1000.0,
        location_code: "",
        highest_price: 1500.0,
        created: "2022-06-16T09:28:47Z",
        transaction_fee_configurations: [
          {
            order_type: "Sell",
            fee_name: "VAT",
            fee_description: null,
            fee_value: 7.5,
            fee_type: "vat",
            fee_structure_type: "unit",
          },
          {
            order_type: "Buy",
            fee_name: "Exchange Fee",
            fee_description: null,
            fee_value: 0.5,
            fee_type: "percentage",
            fee_structure_type: "unit",
          },
          {
            order_type: "Buy",
            fee_name: "SEC Fee",
            fee_description: null,
            fee_value: 0.3,
            fee_type: "percentage",
            fee_structure_type: "unit",
          },
          {
            order_type: "Sell",
            fee_name: "Exchange Fee",
            fee_description: null,
            fee_value: 0.5,
            fee_type: "percentage",
            fee_structure_type: "unit",
          },
          {
            order_type: "Sell",
            fee_name: "Collateral Management",
            fee_description: null,
            fee_value: 0.7,
            fee_type: "percentage",
            fee_structure_type: "unit",
          },
          {
            order_type: "Buy",
            fee_name: "VAT",
            fee_description: null,
            fee_value: 7.5,
            fee_type: "vat",
            fee_structure_type: "unit",
          },
        ],
      },
      {
        security_code: "SCSN",
        board: "Spot",
        price: 250.0,
        lowest_price: 245.0,
        location_code: "",
        highest_price: 250.0,
        created: "2022-06-16T09:28:29Z",
        transaction_fee_configurations: [
          {
            order_type: "Buy",
            fee_name: "Exchange Fee",
            fee_description: null,
            fee_value: 0.5,
            fee_type: "percentage",
            fee_structure_type: "unit",
          },
          {
            order_type: "Buy",
            fee_name: "SEC Fee",
            fee_description: null,
            fee_value: 0.3,
            fee_type: "percentage",
            fee_structure_type: "unit",
          },
          {
            order_type: "Sell",
            fee_name: "Exchange Fee",
            fee_description: null,
            fee_value: 0.5,
            fee_type: "percentage",
            fee_structure_type: "unit",
          },
          {
            order_type: "Sell",
            fee_name: "Collateral Management",
            fee_description: null,
            fee_value: 0.7,
            fee_type: "percentage",
            fee_structure_type: "unit",
          },
          {
            order_type: "Buy",
            fee_name: "VAT",
            fee_description: null,
            fee_value: 7.5,
            fee_type: "vat",
            fee_structure_type: "unit",
          },
          {
            order_type: "Sell",
            fee_name: "VAT",
            fee_description: null,
            fee_value: 7.5,
            fee_type: "vat",
            fee_structure_type: "unit",
          },
        ],
      },
    ],
    message: "Latest Security Prices",
  };



  export default data;